"""add user table

Revision ID: 1d089dcab7f0
Revises: a14d994faab2
Create Date: 2026-03-14 10:16:46.967716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d089dcab7f0'
down_revision: Union[str, Sequence[str], None] = 'a14d994faab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verifiend', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('varification_token', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'varification_token')
    op.drop_column('users', 'is_verifiend')
    # ### end Alembic commands ###
