"""add user table

Revision ID: 62a4ff114778
Revises: 1d089dcab7f0
Create Date: 2026-03-14 11:25:09.896959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a4ff114778'
down_revision: Union[str, Sequence[str], None] = '1d089dcab7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_verifiend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verifiend', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
