"""create user table

Revision ID: a14d994faab2
Revises: 
Create Date: 2026-03-08 15:35:54.467845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14d994faab2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', name='role'), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE users SET role='user' WHERE role IS NULL")      
    op.alter_column('users', 'role', nullable=False)
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###  
